### PR TITLE
Add test models for large Modelica arrays in tables

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by tbeu** [comment]
@casella What do you think?

**Comment by casella** [comment]
I always had mixed feelings about the tables, as in the past they have given me more than one headache. On the other hand, this could actually be a good motivation to include them here, so they are more thoroughly tested.

A few specific questions before merging your PR:

- are there any use-cases for tables with one million data points? That corresponds to about one week sampled at 1 second or about two years sampled at 1 minute.
- the experiment annotation only specifies the end time. I guess the simulation performance (particularly event handling) will depend a lot on the integration algorithm and on the communication interval. What do you want to test here? Should we specify a number of intervals equal to N, or see how the tool figures out automatically?

**Comment by tbeu** [comment]
The table tests serve three things
* Benchmark translation performance (with increasing N)
* Benchmark simulation performance (both with regard to increasing N and TimeTable vs. CombiTimeTable as each of the test models creates N time events). Once we have new MSL v3.2.3 we can set the CombiTimeTable model to also interpolate linearly and still get the time events at the interval boundaries.
* Benchmark utilized memory during simulation (with increasing N)

I scaled up the experiments up to N=1024000 to have it future proof (as I have already seen arrays up to 100000 points from users).

**Comment by casella** [comment]
OK, sounds good. I'll accept the pull request, do some experiments with OMC, get back to you and finally make a new release, so this also gets into the OpenModelica testsuite

**Pull request merged**
